<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Delete_duplicates extends CI_Controller {
 function __construct()    {        // Construct the parent class        parent::__construct();		$this->load->library("CI_Jwt");         // Configure limits on our controller methods    }
 
	public function index() 
	{		$duplicates_rs = $this->db->query("select * from duplicate_records where  updated_status='no'  limit 0,50");		foreach($duplicates_rs->result() as $dup_row)		{			$school_id = $dup_row->school_id;			$item_id = $dup_row->item_id;			$entry_date = $dup_row->entry_date;			 $bs_list =$this->db->query("select * from balance_sheet where school_id=? and item_id=? and entry_date=? order by entry_id desc  "										,array($school_id,$item_id,$entry_date));			 			$entry_ids_list = array();			foreach($bs_list->result() as $row)			{				$entry_ids_list[] = $row->entry_id;			}			$dont_delete_entry_id = min($entry_ids_list);			foreach($entry_ids_list as $entry_id){								if($entry_id == $dont_delete_entry_id)					continue;						 $this->db->query("delete from balance_sheet where  				(purchase_quantity = 0 and session_1_qty + session_2_qty+session_3_qty+session_4_qty=0) 				 and  school_id = ?				and item_id = ? 				and entry_date =? 				and entry_id = ? 								",array($school_id,$item_id,$entry_date,$entry_id));				echo "<br>Deleted Count ".$this->db->affected_rows();			}																$this->db->query("update duplicate_records set updated_status='yes' where school_id=? and item_id=? and entry_date=?",array($school_id,$item_id,$entry_date));								}	}	public function showcount()	{		$rs = $duplicates_rs = $this->db->query("SELECT school_id,item_id,entry_date,count(*) as record_count FROM `balance_sheet` 	group by school_id,item_id,entry_date having record_count > 1");		echo "Duplicates : " . $rs->num_rows();	}	  
}
