<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Readatdos extends CI_Controller {
 function __construct()    {        // Construct the parent class        parent::__construct();		$this->load->library("CI_Jwt"); 		$this->load->library("excel");         // Configure limits on our controller methods    }
 
	public function index()
	{		$file = 'assets/uploads/atwos.xls';									$objPHPExcel = PHPExcel_IOFactory::load($file);									 									//get only the Cell Collection									$cell_collection = $objPHPExcel->getActiveSheet()->getCellCollection();									 									//extract to a PHP readable array format									foreach ($cell_collection as $cell) {										$column = $objPHPExcel->getActiveSheet()->getCell($cell)->getColumn();										$row = $objPHPExcel->getActiveSheet()->getCell($cell)->getRow();										$data_value = $objPHPExcel->getActiveSheet()->getCell($cell)->getValue();									 										//header will/should be in row 1 only. of course this can be modified to suit your need.										if ($row == 1) {											$header[$row][$column] = $data_value;										} else {											$arr_data[$row][$column] = $data_value;										} 									}															$queries = array();						foreach($arr_data as $key=>$obj)						{							// print_a($obj,1 );							//create user id for atdo							$district_id = $obj['C'];							$atdo_id = $obj['D'];							$atdo_name =  $atdo_location = $obj['E'];							//check if atdo user already exists							$users_rs = $this->db->query("select * from users where school_code=?",array($atdo_id));							//echo $this->db->last_query(),"<br>";;die;							if($users_rs->num_rows()==0)							{								$ins_data = array();								$ins_data['district_id'] = $district_id;								$ins_data['is_dco'] = 1;								$ins_data['is_atdo'] = 1;								$ins_data['school_code'] = $atdo_id;								$ins_data['ddo_code'] = $atdo_id;								$ins_data['utype'] = 'subadmin';								$ins_data['name'] = $atdo_name;								$ins_data['atdo_location'] = $atdo_location;								$ins_data['email'] = $atdo_id;								$ins_data['password'] = md5('123456');								$this->db->insert("users",$ins_data);							}							//ATDO USER ID 							$user_id = $this->db->query("select * from users where school_code=?",array($atdo_id))->row()->uid;																					$school_ddo_code  = $obj['F'];														$school_rs  = $this->db->query("select * from schools  where school_code=?",array($school_ddo_code));							if($school_rs->num_rows()>0)							{								$school_id  = $school_rs->row()->school_id;								$assigned_rs  = $this->db->query("select * from assigned_schools  where user_id=? and school_id=?" ,array($user_id,$school_id));								if($assigned_rs->num_rows()==0){									$ins2_data = array();									$ins2_data['user_id'] = $user_id;									$ins2_data['school_id'] = $school_id; 									$this->db->insert("assigned_schools",$ins2_data);								}															} 						}						echo "Done";die;	} 
}
