<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Readdata extends CI_Controller {
 function __construct()    {        // Construct the parent class        parent::__construct();		$this->load->library("CI_Jwt"); 		$this->load->library("excel");         // Configure limits on our controller methods    }
 
	public function index()
	{		$file = 'assets/uploads/twd.xls';									$objPHPExcel = PHPExcel_IOFactory::load($file);									 									//get only the Cell Collection									$cell_collection = $objPHPExcel->getActiveSheet()->getCellCollection();									 									//extract to a PHP readable array format									foreach ($cell_collection as $cell) {										$column = $objPHPExcel->getActiveSheet()->getCell($cell)->getColumn();										$row = $objPHPExcel->getActiveSheet()->getCell($cell)->getRow();										$data_value = $objPHPExcel->getActiveSheet()->getCell($cell)->getValue();									 										//header will/should be in row 1 only. of course this can be modified to suit your need.										if ($row == 1) {											$header[$row][$column] = $data_value;										} else {											$arr_data[$row][$column] = $data_value;										} 									}															$queries = array();						$this->db->query("TRUNCATE tw_vendors");						//echo $this->db->last_query();die;						foreach($arr_data as $key=>$obj)						{							 //print_a($obj,1);							  $ddo_code = $obj['E'];							 $school_id = 0 ;							 $school_rs = $this->db->query("select * from schools where school_code=?",array($ddo_code));							 if($school_rs->num_rows()>0)							 {								$school_id = $school_rs->row()->school_id;							 }							 							$queries  = "insert into  tw_vendors set hostel_type='".$obj['B']."',														school_id='".$school_id."',														ehostel_id='".$obj['C']."',														hostel_name='".$obj['D']."',														ddo_code='".$obj['E']."',														ehostel_vendor_id='".$obj['F']."',														vendor_name='".$obj['G']."',														business_nature='".$obj['H']."',														tin_number='".$obj['I']."',														vendor_address='".$obj['J']."',														vendor_contact_number='".$obj['K']."',														supplier_name='".$obj['L']."',														supplier_contact_number='".$obj['M']."',														vendor_bank='".$obj['N']."',														vendor_bank_branch='".$obj['O']."',														vendor_bank_ifsc='".$obj['P']."',														vendor_account_number='".$obj['Q']."',														supplier_aadhar_number ='".$obj['R']."'";							$this->db->query($queries);													}					//	echo implode(";<br>",$queries);die;	} 
}
