<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>:: Annapurna.in.net | Welcome To Annapurna Menu Monitering Software Andhra PradeshAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, andhra pradesh social welfare residential educational institutions societyAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, APSWREISAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, APTWREISAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, GURUKUL VIDYALAYAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, gurukul pathshala Andhra PradeshAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, APSWREI Society - Centre for Good Governance





APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, VISAKHAPATNAM (BOYS & GIRLS)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

PULIVENDULA  COE(BOYS & GIRLS)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

DUPPALAVALASAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

ETCHERLAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KANCHILIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

SRIKAKULAM (Peddapadu)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KOLLIVALASAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

NANDIGAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

PALAKONDAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

TAMARAPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

BADANGIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

BHAMINI APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KOPPERLAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

MANDASA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

SALURUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

VANGARA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL  COE,

PARVATHIPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

PATHAPATNAM  APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 

DEVARAPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

NELLIMARLA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

GOLUGONDAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

VIYYAMPET APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

SABBAVARAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

VEPADA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

SRIKRISHNAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

KOMARADA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

LAXMINARASAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

GARUGUBILLI APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

A.MALLAVARAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

NAKKAPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

ALLAVARAM AT GODI (B)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

MEGADRIGADDAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,       

KOTTURU (JC)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

MADUGULA / KONAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

P.GANNAVARAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

NARSIPATNAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

DRAKSHARAMAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

TALLAPALEMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

ARUGOLANUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

KOKKIRAPALLYAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

PEDAVEGIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

P.VENKATAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

NARSAPURAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

S.M.NAGAR APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

CHINTALAPUDIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

YELESWARAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

RUDRAVARAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

TUNI APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KRISHNARAOPALEMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

DOWLAISWARAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 

RAJAHMUNDRY

TIRUVURUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

MUMMIDIVARAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

PAMMARRUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

RAZOLEAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 KarempudiAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

JAGGAMPETAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

AtchampetaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

VEERALANKAPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

Tsundur	GODI (G)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

NizampatnamAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

CHOLLANGIPETAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

TadikondaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

PITHAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

GurazalaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

POLASANIPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

AdavithakkellapaduAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

ELURU / VATLURUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

VelugondaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

JANGAREDDYGUDEMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

ArdhaveeduAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

KOVVURUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

DarsiAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

KOMATIKUNTAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

ChillakurAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,  	

DWARAKA TIRUMALAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KotaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

ACHANTA

Naidupeta  (Convenor)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

KUNTAMUKKALAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

Mulapadava / VakaduAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

JAGGAIAHPETAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

BogoleAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	NUZIVEEDU (G)

RAMAKUPPAM (U.G)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

GUDIVADAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

B. KOTHAKOTAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

NANDIGAMA / MUPPALLAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

VIJALAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

NARSAPURAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

B. MATTAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

CHALLAPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

RAMAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

NANDAMUR/BalliparruAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

SAGILERUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

VEDURUPAVULURU APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 VEERPANENIGUDEMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

GANDIKSHETRAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

RANGAPURAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

RLY.KODURUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

RamakrishnapuramAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

PULIVENDULAAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

V.P.South/N.SagarAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KALASAMUDRAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

BapatlaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

MALUGURUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

VinukondaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

KANEKALAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

RepalleAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

C. BELGALAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,	

Uppalapadu(Nuzendlamandalam)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

JUPADU BANGAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

Amaravathi (Convenor)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

CHINNATEKURAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 	

KakumanuAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	PedapavaniAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	ChimakurthyAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	Singarayakonda APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	CumbumAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	DupaduAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	MarkapurAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	Nagulapalem (Convenor)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	North AddankiAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KondepiAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	RacherlaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	YeddanapudiAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	MuthukurAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	DakkiliAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	Rapur / KandaleruAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	SullurrpetaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	BuchireddypalemAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	Sarvepalli at KodurAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	SangamAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	Pudur at NaidupetaAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	AdurupalliAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	SRIKALAHASTIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	CHITTOORAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 

 	PILERUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, 

 	BURAKAYALAKOTA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,    

 	PALAMANERU APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	SATYAVEEDU APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	PUTTUR APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	MADANAPALLIAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KUPPAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	VALMIKIPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	GANGADHAR NELLOREAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	PUTHALAPATTUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	CHINNA CHOWK APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KAMALAPURAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	RAYACHOTY APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	DEVAPATLA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	ADAPURU APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	THONDURU APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	GUNDLAKUNTA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	MADAKALAVARIPALLI APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	LAKKIREDDY PALLI APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	RAJUPALEM   APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KONDAPURAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KURUGUNTA Dr.BRAC JCAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	THIMMAPUR APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	NALLAMADA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	URAVAKONDA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	B. PAPPUR APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KURUGUNTA JCAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	GOOTY APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	BRAHMASAMUDRAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	AMARAPURAM APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	HINDUPUR APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KORAPADUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	ALURU(Arikera) APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KOILAKUNTLA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	DINNADEVARAPADUAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, KURNOOL(BCamp)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	PEAPALLY / DHONE APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	ALLAGADDA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	ADONI APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	VELDURTHY APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	PATTIKONDA APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	KAMBALLAPADU APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	LAXMAPURAMAPSWREI SOCIETY JUNIOR COLLEGE/SCHOOL,

 	ALLAGADDA (RPRP)APSWREI SOCIETY JUNIOR COLLEGE/SCHOOL, ::</title>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<?php $this->load->view("site_css");?>
<table width="100%">
 	<tr>		<td style="background-color:#FFF">
	
	
		
<img src="<?php echo site_url();?>images_swf/log.png" width="700" height="100" />
	
</td></tr> 
	<tr>		<td >

<!----MENU LIST START-->
 
<table width="100%" border="0" cellspacing="0" cellpadding="0">

  <tr>

    <td class="ddsmoothmenu"><div id="smoothmenu1" class="ddsmoothmenu">

                <ul>

                  <li> <a href="<?php echo site_url();?>" <?php if($this->uri->segment(1)=="") { echo ' class="selected"  ';} ?>>Home</a></li> 
                

                  <li><a  <?php if($this->uri->segment(1)=="dreport") { echo ' class="selected"  ';} ?>href="<?php echo site_url("dreport/frame"); ?>"  >DIET Expenditure</a>                  </li> 
                </ul>

              <br style="clear: left" />

    </div></td>

  </tr>



</table>
 


<!----MENU LIST END-->




	</td></tr>

	<tr><td>   