<?php  echo $this->session->flashdata('message'); $ses_p = $this->consumption_model->get_authorise($session_id,$this->session->userdata("school_id"));?>
<h3>Vendors List</h3>
 <style>table {  border-collapse: collapse;  width: 100%;}th, td {  text-align: left;  padding: 8px;}tr:nth-child(even) {background-color: #f2f2f2;}table#vendors {    font-size: 16px;    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;    border-collapse: collapse;    border-spacing: 0;    width: 100%;}#vendors td, #vendors th {    border: 1px solid #ddd;    text-align: left;    padding: 8px;}#vendors th {    padding-top: 11px;    padding-bottom: 11px;    background-color: #4CAF50;    color: white;}.tlable{	font-weight:bold;}</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> 
<div class="box">
          
            <!-- /.box-header --><br><br>			<div style="padding-right:50px;" ><a href='<?php echo site_url();?>vendors/entryform' class='btn btn-info pull-right' >Add new Vendor</a></div><br><br>
            <div class="box-body">
               <?php if($vendors->num_rows()==0){					echo "<h1>No vendors found</h1>";			   }			   ?>
			  <span><b><h4>Total Vendors  : <?php echo $vendors->num_rows();?></h4></span>			<?php $sno = 1; foreach($vendors->result() as $row) { ?>
			  <table id="example1" class="table vendors table-bordered">			  <thead><tr><th colspan="12" style="background-color:#119936;color:#FFF;font-weight:bold;">Vendor <?php echo $sno;?></th></tr></thead>			  <tbody>						<tr><td><span class='tlable'>Vendor Type</span></td><td><span class='tvalue'><?php echo ucfirst($row->vendor_type);?></span></td></tr>						<tr><td><span class='tlable'>Vendor name</span></td><td><span class='tvalue'><?php echo $row->vendor_name;?></span></td></tr>						<tr><td><span class='tlable'>Business_nature</span></td><td><span class='tvalue'><?php echo $row->business_nature;?></span></td></tr>						<tr><td><span class='tlable'>Tin number</span></td><td><span class='tvalue'><?php echo $row->tin_number;?></span></td></tr>						<tr><td><span class='tlable'>Vendor address</span></td><td><span class='tvalue'><?php echo $row->vendor_address;?></span></td></tr>						<tr><td><span class='tlable'>Vendor contact number</span></td><td><span class='tvalue'><?php echo $row->vendor_contact_number;?></span></td></tr>						<tr><td><span class='tlable'>Supplier name</span></td><td><span class='tvalue'><?php echo $row->supplier_name;?></span></td></tr>						<tr><td><span class='tlable'>Supplier contact number</span></td><td><span class='tvalue'><?php echo $row->supplier_contact_number;?></span></td></tr>						<tr><td><span class='tlable'>Vendor bank</span></td><td><span class='tvalue'><?php echo $row->vendor_bank;?></span></td></tr>						<tr><td><span class='tlable'>Vendor bank branch</span></td><td><span class='tvalue'><?php echo $row->vendor_bank_branch;?></span></td></tr>						<tr><td><span class='tlable'>Vendor bank ifsc</span></td><td><span class='tvalue'><?php echo $row->vendor_bank_ifsc;?></span></td></tr>						<tr><td><span class='tlable'>Vendor account number</span></td><td><span class='tvalue'><?php echo $row->vendor_account_number;?></span></td></tr>						<tr><td><span class='tlable'>Supplier aadhar number</span></td><td><span class='tvalue'><?php echo $row->supplier_aadhar_number;?></span></td></tr>						</tbody>			  </table>			  <br><br>			<?php $sno++;} ?>			  			  </div>
		   
	 