<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Readstrengths extends CI_Controller {
 function __construct()    {        // Construct the parent class        parent::__construct();		$this->load->library("CI_Jwt"); 		$this->load->library("excel");         // Configure limits on our controller methods    }
 
	public function index()
	{		$file = 'assets/uploads/premetric_schools.xls';									$objPHPExcel = PHPExcel_IOFactory::load($file);									 									//get only the Cell Collection									$cell_collection = $objPHPExcel->getActiveSheet()->getCellCollection();									 									//extract to a PHP readable array format									foreach ($cell_collection as $cell) {										$column = $objPHPExcel->getActiveSheet()->getCell($cell)->getColumn();										$row = $objPHPExcel->getActiveSheet()->getCell($cell)->getRow();										$data_value = $objPHPExcel->getActiveSheet()->getCell($cell)->getValue();									 										//header will/should be in row 1 only. of course this can be modified to suit your need.										if ($row == 1) {											$header[$row][$column] = $data_value;										} else {											$arr_data[$row][$column] = $data_value;										} 									}								//	print_a($arr_data,1);						$queries = array();						foreach($arr_data as $key=>$obj)						{							 //print_a($obj,1);							 $ddo_code = $obj['F'];							 $contact_number = $obj['I'];							 $school_id = 0 ;							 $school_rs = $this->db->query("select * from schools where school_code=?",array($ddo_code));							 if($school_rs->num_rows()>0)							 {								$school_id = $school_rs->row()->school_id;								$this->db->query("update schools set contact_number=? where school_id=?",array($contact_number,$school_id ));							 }							 $classes = array("1"=>"L","2"=>"M","3"=>"N","4"=>"O","5"=>"P","6"=>"Q","7"=>"R","8"=>"S","9"=>"T","10"=>"U");							foreach( $classes as $class_id=>$excel_col){ 							$query = "insert into  school_class_strengths set  														school_id='".$school_id."',														ddo_code='".$ddo_code."',														class_id='".$class_id."',														strength='".$obj[$excel_col]."',														start_date='2019-01-01',														end_date='2023-09-01' ";								$this->db->query($query);											echo "<br>",$this->db->last_query(),"<br>";							}																																			}						echo  "Completed ";	} 
}
